package oop0318;

class Test{
	//1) try ~catch 직접이용한 예외처리
	public void view() {
		try {
			int a = Integer.parseInt("korea");
		}catch(Exception e) {
			System.out.println(e);
		}
	}
	//2) throw 를 이용한 예외처리
	public void disp() throws Exception{
		System.out.println(1/0);
	}
	
	public void doSomething() throws NullPointerException, NumberFormatException{
		int a = Integer.parseInt("korea");
		System.out.println(a);
	}
	
}

public class Test04_throws {

	public static void main(String[] args) {
		// 예외를 던진다
		//-> 메소드 호출 시 예외처리를 한꺼번에 모아서 처리한다
		Test t = new Test();
		
		try{t.disp();
		t.doSomething();}
		catch(Exception e) {
			System.out.println(e);
		}
	}
	

}
